apiVersion: v2
name: pack-ship-service
description: Packing and shipping with 3D bin packing
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
- paklog
- warehouse
- wms
- microservices
maintainers:
- name: Paklog Team
